import { Alegreya_Sans, Montez, Mulish, Alegreya_Sans_SC } from "next/font/google";
import "./globals.css";
import Header from "./sections/Header";

const AlegreyaSans = Alegreya_Sans({ subsets: ["latin"], weight: "400" });
const MontezFont = Montez({ subsets: ["latin"], weight: "400" });
const MulishFont = Mulish({ subsets: ["latin"], weight: ["400", "700"] });
const AlegreyaSansSC = Alegreya_Sans_SC({ subsets: ["latin"], weight: "400" });
export const metadata = {
	title: "Martina Doekharan",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${AlegreyaSans.variable} ${MontezFont.variable} ${MulishFont.variable} ${AlegreyaSansSC.variable} antialiased`}
			>
			<Header />

				{children}
			</body>
		</html>
	);
}
